version: "3.8"
services:
  app:
    build: ./infra/php
    volumes:
      - ./backend:/work
  nginx:
    image: nginx:1.18-alpine
    ports:
      - 10080:80
    volumes:
      - ./backend:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work
  mariadb:
    ports:
      - 10070:3306
    build: ./infra/mariadb
    volumes:
      - db-store:/var/lib/mariadb

volumes:
  db-store:
